name: Pytest

on:
  pull_request:
    branches:
      - main

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          grep -v pywin32 requirements.txt | pip install -r /dev/stdin
          pip install pytest

      - name: Run tests
        run: |
          echo '{"token": "test-token", "game_number": 46, "gamestate_path": "/tmp/eclipse_test_games"}' > config.json
          python3 -m pytest tests/
          
